app = "lift-proxy"
primary_region = "syd"
swap_size_mb = 512

[build]
dockerfile = "standalone.Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
