CREATE TABLE IF NOT EXISTS auth (
  id SERIAL PRIMARY KEY,
  provider TEXT NOT NULL,
  api_key TEXT NOT NULL UNIQUE,
  sent INTEGER NOT NULL DEFAULT 0,
  max INTEGER NOT NULL DEFAULT 0,
  valid BOOLEAN NOT NULL DEFAULT TRUE,
  used_at TIMESTAMPTZ DEFAULT '1970-01-01 00:00:00',
  cooldown BOOLEAN NOT NULL DEFAULT FALSE,
  comments TEXT
);
